/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "2.7.4"
    id("io.spring.dependency-management") version "1.0.14.RELEASE"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-zuul:2.2.10.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.7.1")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:3.1.3")
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign:3.1.3")
    implementation("org.springframework.data:spring-data-cassandra:3.4.1")
    implementation("javax.servlet:javax.servlet-api:4.0.1")
    implementation("org.springframework.boot:spring-boot-starter-security:2.7.1")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("org.springframework.security.oauth:spring-security-oauth2:2.3.3.RELEASE")
    implementation("org.springframework.security:spring-security-jwt:1.0.9.RELEASE")
    implementation("org.springframework.boot:spring-boot-devtools:2.7.1")
    implementation("org.springframework.boot:spring-boot-starter-mail:2.5.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.1")
}

group = "io.asyph"
version = "0.0.1-SNAPSHOT"
description = "AsyphAuthService"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
