FROM redis:7.0.5-alpine
RUN apk update && \
    apk add openjdk17-jre-headless && \
    apk add supervisor
COPY ApiGateway/build/libs/ApiGateway-0.0.1-SNAPSHOT.jar gateway.jar
COPY OnlineJudge/build/libs/OnlineJudge-0.0.1-SNAPSHOT.jar judge.jar
COPY UserMicroservice/build/libs/UserMicroservice-0.0.1-SNAPSHOT.jar user-service.jar
COPY ProblemsAndContestService/build/libs/ProblemsAndContestService-0.0.1-SNAPSHOT.jar problem-service.jar
COPY supervisord.conf /etc/supervisord.conf
ARG GMAIL_APP_PASSWORD
ENV GMAIL_PASSWORD=GMAIL_APP_PASSWORD
EXPOSE 8080
EXPOSE 8085
EXPOSE 8086
EXPOSE 8081
EXPOSE 6379
ENTRYPOINT ["/usr/bin/supervisord"]
