/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "2.7.4"
    id("io.spring.dependency-management") version "1.0.14.RELEASE"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-cassandra:2.7.1")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.1")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:3.1.3")
    implementation("org.springframework.boot:spring-boot-starter-webflux:2.7.1")
    implementation("org.quartz-scheduler:quartz:2.3.2")
    implementation("log4j:log4j:1.2.17")
    implementation("org.springframework.boot:spring-boot-starter-data-redis:2.7.1")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.1")
}

group = "io.asyph"
version = "0.0.1-SNAPSHOT"
description = "ProblemsAndContestService"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
